#!/bin/bash

domain="xn--david-9u04d.to"
cover="https://david.wolf.gdn/media/cover.png"

if [ ! -z "$1" ]; then
    date=$1
else
    date=$(date '+%Y-%m-%d')
fi

filename="${date}_.md"

frontmatter="---
title: 
slug: 
tags: 
lastmod: ${date}
date: ${date}
cover: ${cover}
domain: ${domain}
---"

echo "$frontmatter" >"$filename"
