#!/bin/bash

if [ ! -z "$1" ]; then
    date=$1
else
    date=$(date '+%y-%m-%d')
fi

filename="${date}_.md"

frontmatter="---
title: 
slug: 
tags: 
lastmod: ${date}
date: ${date}
cover: https://david.wolf.gdn/media/cover.png
domain: xn--david-9u04d.to
---"

echo "$frontmatter" >"$filename"
