---
title: "Why nearly all blogs have a terrible user experience + how you can do better"
date: 2021-11-12T21:24:26+01:00
lastmod: 2021-11-12T21:24:26+01:00
draft: true
schemas: [BlogPosting]
---

:icons: font
:caption!:

When searching for something specific on the web and finally finding a link to an article or blog posting which I think could possibly be an answer/solution for what I am looking for and checking out that ressouce - what do I get?

Well, a whole bunch of stuff to be honest. There are so many diffent types of content provided by the website that I am actually *not looking for. Propably there are overlaoded sidebars, giant headers and eventually even ads or pop-ups. That sucks. There is only that one reason I decided to click on that link taking me to that wesite and that's the thought that webpage can help me solve my problem. Instead I get a sweet collection of useless shit.

== Different types of content
So, in order to decide what parts of the website are interesting and which aren't we have to break down that entire mess.

Bascially, we can go ahead and group all the different types of content into three main categories of content:

=== 1. Page related content
First of all, obviously there is the main page content itself. In case of a blog thats an individual and unique (hopefully unique) posting.

Elements which are directly related to the post include: 

* the post title
* the post content

And that's the exactly the content I am looking for as a page vistor and reader. That's what I am expecting. I only went on the page because if this.

Other directly related post 

=== 2. Domain related content
Beside of the 

=== 3. Not related content
Beside of the 